### ISSUE TITLE
GTS FAILED TO LOAD

### ISSUE THREAD

**Issue by locpx92** [NickImpact/GTS#100]
**What is the bug?**
Can't load gts plugin

**What version of GTS are you running?**
GTS (gts) version 6.0.10
ImpactorAPI (impactor) version 3.0.0

**What version of Sponge are you running?**
Minecraft Version: Minecraft 1.12.2
Sponge Version: SpongeForge 1.12.2-2838-7.3.0
Sponge API Version: SpongeAPI 7.3-7127e0882
Nucleus Version: 2.2.7 (Git: c1d51da55)

**Provide a link to the file generated by `/nucleus info`**
https://gist.github.com/locpx92/da6fcc3ede82c2cfdc6a83dc81bfc7c7

**To Reproduce**

**Expected behavior**

**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!
https://gist.github.com/locpx92/ffe4d5be2053a698764293cf8e338183

**Comment by VOrlando520** [comment]
Literally says it in the error log. You are missing another dependency

**Comment by locpx92** [comment]
Could you tell me, which one is missing?

**Comment by NickImpact** [comment]
Check the first line of the error, and the answer is there.

**Comment by locpx92** [comment]
I use protocolcontrol-0.0.2.jar, and getting new error:

https://gist.github.com/locpx92/5d0b144d2afe0ddd5f42b477b1aecfb0

**Comment by EleZer0** [comment]
Still looks like Protocol Control error, I believe it has to be directly in your mods folder. Not in a plugins/mods folder inside mods if that is something you do. 

Might also help for future support questions to ask directly into the discord, there's link on the homepage on Ore.
https://ore.spongepowered.org/NickImpact/GTS

**Comment by locpx92** [comment]
Thanks you all for supporting, I checked the protocolcontrol-0.0.2.jar file, there is a system error while copying the file into mods folder. Now the plugin is loaded successful.
