### ISSUE TITLE
Starting issue

### ISSUE THREAD

**Issue by kasdo** [NickImpact/GTS#101]
Can't run plugin
https://hastebin.com/tidibugigo.css

Mods and plugins:
![image](https://user-images.githubusercontent.com/7419546/103200329-b709eb00-48f5-11eb-8f3c-c3d1fd990bcc.png)

Sponge:
![image](https://user-images.githubusercontent.com/7419546/103200345-c5f09d80-48f5-11eb-81f2-c3fb9457919f.png)

**Comment by NickImpact** [comment]
Install protocol control, as that’s what the error tells you to do
