### ISSUE TITLE
Getting New Error

### ISSUE THREAD

**Issue by BlankSans** [NickImpact/GTS#104]
I need help
sponge 7.3.0
impact 3.0.0
gts 6.0.10

[latest.log](https://github.com/NickImpact/GTS/files/5759026/latest.log)

**Comment by 02Miki** [comment]
You are probably missing protocol control, I cannot check as I’m on the phone

**Comment by BlankSans** [comment]
I have protocol control 0.0.2

**Comment by 02Miki** [comment]
Upload the log to pastebin please

**Comment by BlankSans** [comment]
https://pastebin.pl/view/6348e361

**Comment by NickImpact** [comment]
Please start using the issue templates, or I will start **closing and locking your tickets with no response** until you do so.

As for your issue, the repository hosting the command framework appears unavailable. You'll unfortunately have to wait until it's available, or you can go ask someone in the community to provide you their already downloaded versions of it.
