### ISSUE TITLE
Error in console when using anvil

### ISSUE THREAD

**Issue by marteinnsi** [NickImpact/GTS#106]
**What is the bug?**
Console is flooded with errors when anvils are used

**What version of GTS are you running?**
GTS-Sponge-6.0.11.jar

**What version of Sponge are you running?**
SpongeVanilla
Minecraft: 1.12.2
SpongeAPI: 7.3-7127e0882
Sponge: 1.12.2-7.3.0
SpongeVanilla: 1.12.2-7.3.0
JVM: 1.8.0_271/64-bit (Oracle Corporation)
**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.

**To Reproduce**
1. Install this plugin
2. Use an anvil
3. Get errors in console!

**Expected behavior**
No errors in the console

**Error logs**
https://gist.github.com/marteinnsi/038af60b2587467878bd051fbf99e569

**Comment by NickImpact** [comment]
So just to verify, this is on a SpongeVanilla instance?

**Comment by NickImpact** [comment]
Confirmed to be a SpongeVanilla issue, I imagine I was using a method provided by a forge patch without realizing.

**Comment by NickImpact** [comment]
Fix in next upcoming version
