### ISSUE TITLE
Item Dupe

### ISSUE THREAD

**Issue by Druwan-ctrl** [NickImpact/GTS#107]
**What is the bug?**
Item duplication with a slow/tampered with internet connection

**What version of GTS are you running?**
GTS-Sponge-6.0.11

**What version of Sponge are you running?**
spongeforge-1.12.2-2838-7.3.0

**Provide a link to the file generated by `/nucleus info`**
[Link](https://www.dropbox.com/s/yeg1lk15lhhe162/nucleus-info-20210114-082909.txt?dl=1)

**To Reproduce**
1. Make yourself lag 
2. Run multiple /gts commands without receiving the gui
3. When the first gui appears, take one item of your choosing
4. If you do not take them all, the next gui that opens will be the next screen
5. Proceed like this until you get to the desired item
6. Dupe...

**Expected behavior**
If a player is lagging too hard, only one screen should be able to open so he cannot steal anything of value

**Comment by NickImpact** [comment]
They’re ghost items. All transactions with the interface are cancelled to prevent taking the item. They do not exist, no matter how laggy it is. And if you’re server is that laggy, you have other issues you need to deal with.

**Comment by Druwan-ctrl** [comment]
The server was not lagging, only me. I had a friend online that was perfectly fine, tps at 20 in all dimensions. They're not ghost items, i could place them and drop them

**Comment by 02Miki** [comment]
If you are the one lagging, then it's even more impossible. You could probably place blocks, yea, but it would only be client-side. As soon as you relog, those blocks will vanish. This will happen with any UI

**Comment by Druwan-ctrl** [comment]
Maybe the fact that I was in creative could give me the impression of the dupe then, will try again!

**Comment by hutchy50** [comment]
Being in creative might do it as it syncs inventories from client to server. When testing dupes always test in survival.
