### ISSUE TITLE
Everyone has access to /gts admin

### ISSUE THREAD

**Issue by SnowBlitzz** [NickImpact/GTS#11]
It seems like everyone can do /gts admin clear even though no permission was given for it in any group, not even a staff group. 

P.S. (small side-note) You forgot to turn off debug messages for /gts help https://pastebin.com/e2CpFtGr

**Comment by Zimon4eR** [comment]
Ok, since permissions poorly made in here, just do like i did on my server.
default permissions:
gts.command.gts true
gts.command.gts.admin false

staff perm:
gts.command.gts.admin true

**Comment by SnowBlitzz** [comment]
I don't understand what you mean @Zimon4eR 
`gts.command.gts.admin` is not the permission for admin according to the wiki https://github.com/NickImpact/GTS/wiki/Commands

Generally I should not need to negate the permission for default. They should naturally not be able to access it when the permission is unset. What I think is happening here is that there's no permission node set for admin yet, or it's wrong in the wiki >> `gts.command.admin`

**Comment by Zimon4eR** [comment]
"gts.command.gts" works like "gts.command.gts.*", so just try as I told you before..

**Comment by SnowBlitzz** [comment]
Yeah so the wiki has wrong info.. Thanks for the verbose check @Zimon4eR !

**Comment by NickImpact** [comment]
Permissions were registered poorly, should be fixed now!
Commit for fix: 08fd982
