### ISSUE TITLE
Allow blacklisting of Pixelmon Eggs

### ISSUE THREAD

**Issue by Mike5357** [NickImpact/GTS#111]
**What are you trying to do?**
Prevent the listing of unhatched eggs on GTS. We would only like hatched Pixelmon to be listed to the GTS.

**Describe the solution you'd like**
Allow an option to add eggs to the blacklist config.

**Describe alternatives you've considered**
Since eggs are classified by id of the Pixelmon they hatch into themselves, adding them to the current blacklist system might not be feasible and instead a separate "Allow Eggs" option in the config could be an option.

**Comment by Mike5357** [comment]
Follow-up: It's also possible to view that stats of un-hatched eggs before a listing is even posted so the blacklist wouldnt solve the issue unless this was also changed with the config option:
![image](https://user-images.githubusercontent.com/12630858/105399044-12778200-5bf1-11eb-8c18-a610fbb27c28.png)

**Comment by Heriptik** [comment]
Good idea

**Comment by NickImpact** [comment]
I'm willing to do the first option of just outright blocking eggs from being listed, but egg information is shown as to help ensure GTS doesn't become a gambling service. I want people to know what they are buying, rather than guess and then attack you guys because they didn't know what they were buying, which will then of course find a way to lead back to me.

**Comment by Mike5357** [comment]
If eggs were unlistable, then that wouldn't be an issue

**Comment by Mike5357** [comment]
Perhaps a better compromise would be to change the name/lore of any blacklisted item/pokemon in the preview to say "This item is unlistable"?

**Comment by NickImpact** [comment]
Will consider the alternative for 6.1.1. Otherwise, 6.1.0 will ship with being able to block the listing of eggs.
