### ISSUE TITLE
Pokemon with Bottlecaps

### ISSUE THREAD

**Issue by Qumoo** [NickImpact/GTS#113]
**What is the bug?**
When selling a Pokemon hyper-trained with a bottlecap it 
a) does not show up as hyper-trained in the listings
b) loses its hyper-training when returned after not being sold

**What version of GTS are you running?**
You can simply mention the jar's name to ease this process.
The version currently on test.impactdev.net
and GTS-Sponge-6.0.11.jar

**What version of Sponge are you running?**
Please tell us what version of Sponge you're on, so we can triage effectively
7.3.0

**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.
Do we need this anymore? GTS does not depend on nucleus anymore, does it?
(Will deliver nucleus info if asked)

**To Reproduce**
1. Hyper-train a Pokemon with a bottlecap (silver for one stat, gold for all stats)
2. List it in GTS
3. Take it from the GTS
4. See that it is no longer hyper-trained

**Expected behavior**
Pokemon should keep its hyper-training after being listed in the GTS.

**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!

**Comment by NickImpact** [comment]
Fixed in the Cross Pixelmon API version 1.0.2
