### ISSUE TITLE
Hidden Ability Should Be Different Color in the Listing

### ISSUE THREAD

**Issue by Mikirae** [NickImpact/GTS#114]
When ability is shown in GTS, it has one color for every ability.
A clear and concise description of what you're requesting and why you're requesting it. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
Hidden ability should be a different color than normal abilities.

**Describe alternatives you've considered**
Allow us to color per ability.
**Anything else that might help?**
Just you staying hella cute.

**Comment by NickImpact** [comment]
6.1.0 will let you control exactly how you format the two instances now.
