### ISSUE TITLE
No money returned on auction end.

### ISSUE THREAD

**Issue by MageFX** [NickImpact/GTS#115]
**What is the bug?**
Money is not returned to the player when auction is ended nor is it in the #stash if bidding player is offline (reports of if they are online also but couldn't verify)

**What version of GTS are you running?**
Sponge 6.0.11
Reforged 6.0.11b
Impactor 3.1.0

**What version of Sponge are you running?**
7.3.1-RC0

**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.

**To Reproduce**
1. Auction a pokemon
2. Bid on pokemon [Log off]
3. Get outbid
4. Log back on after auction has ended.

**Expected behavior**
Money to be either returned to player or added to stash

**Error logs**
No errors found in logs.

**Comment by NickImpact** [comment]
Fixed in latest 6.1.0 snapshot builds. They are not yet production ready.
