### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LeonusDH** [NickImpact/GTS#116]
When trying to select a price for a product (Item), the GUI closes, and the error is below in the console! And the same effect when trying to select something in /gts admin !

GTS - 6.0.11
GTS-Extension-Reforged - 6.0.11

Sponge - 7.3.0

**To Reproduce**

https://pastebin.com/WS6unA3m

**Comment by NickImpact** [comment]
Read the dependency list and install instructions.
