### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LeonusDH** [NickImpact/GTS#117]
When trying to select a price for a product (Item), the GUI closes, and the error is below in the console! And the same effect when trying to select something in /gts admin !

GTS - 6.0.11
GTS Extension Reforged - 6.0.11
Impactor - 3.1.0-SNAPSHOT
Protocol control - 0.0.2
Economy Plugin - EconomyLite

Sponge - 7.3.0

https://pastebin.com/WS6unA3m

**Comment by NickImpact** [comment]
Don't make duplicate issues. Ensure Protocol Control is in the mods folder and not anywhere else. Verify it boots correctly on startup.
