### ISSUE TITLE
Allow anvil name doesn't work

### ISSUE THREAD

**Issue by zespy12** [NickImpact/GTS#118]
**What is the bug?**
There's a setting in the config that disable the sell of anvil named items to be push on to GTS. After setting it to true , players can still put item with anvil named on GTS

**What version of GTS are you running?**
GTS-Sponge-6.1.2

**What version of Sponge are you running?**
spongeforge-1.12.2-2838-7.3.0

**Provide a link to the file generated by `/nucleus info`**
https://pastebin.com/QuHpG23i.

**To Reproduce**
1. Go to 'allow-anvil-names = true'
2. Rename a Item with a anvil
3. Put it on GTS

**Expected behavior**
Anvil-named item still can be put on GTS 

**Error logs**
There's no error log

**Comment by NickImpact** [comment]
You want this setting set to false. True means as the option specifies, allow it.
