### ISSUE TITLE
GTS failed to load

### ISSUE THREAD

**Issue by xdAmar** [NickImpact/GTS#119]
When  I added the extensions i got an error message and I can't find out what to do the error message is in the txt file 
[Help.txt](https://github.com/NickImpact/GTS/files/6215894/Help.txt)

**Comment by Polymeta** [comment]
You added the PixelmonGenerations extension. 

I assume you are a reforged user, so you need to remove the generations extension and get the correct (reforged for you) extension.

**Comment by xdAmar** [comment]
> You added the PixelmonGenerations extension.
> 
> I assume you are a reforged user, so you need to remove the generations extension and get the correct (reforged for you) extension.

Thanks it works now
