### ISSUE TITLE
Players lose their pokemon when it expires while they're offline

### ISSUE THREAD

**Issue by SnowBlitzz** [NickImpact/GTS#12]
I've gotten over 5 reports from different players missing their Pokemon on my main server. Their balance didn't update so the only way for this to make sense is they didn't get their Pokemon back when they logged in. 

After some tests, I've concluded this only happens after a server restart. I've ran a test on my test server, setting the lot time to 5 minutes. http://puu.sh/z43fy/5e17f417c7.png >> Here's when I added 2 Pokemon in the GTS. Note this is a test server that only I have access to so nobody could every possibly buy my Pokemon. I immediately logged off after putting the Pokemon, restarted the server, and waited 8-10 minutes to make sure they've really expired.

Loggin back in, I lose the Pokemon I put in the GTS. They're neither in my party or my PC. 

Edit: Probably a primary key issue.

**Comment by Flashback083** [comment]
Hey, do you test the pre-release 5 of GTS ?

**Comment by SnowBlitzz** [comment]
This also happens there. There are more reports from other servers on discord.

**Comment by Earthplate** [comment]
I have this error too

**Comment by NickImpact** [comment]
More than likely the primary key issue at fault here, trying to work it out to avoid such

**Comment by PixelmonPRO** [comment]
https://gist.github.com/PixelmonPRO/bdae8ddbd8495c61e1288229ceb8d378
