### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by Jaackla** [NickImpact/GTS#121]
**What is the bug?**
If your party is full and you buy a pokemon it takes it away, it dosent send to the pc at all

2nd bug if you buy a special texture pokemon when you recieve it gts removes the texture and makes it regular form

**What version of GTS are you running?**
You can simply mention the jar's name to ease this process.
Latest and generations

**What version of Sponge are you running?**
Please tell us what version of Sponge you're on, so we can triage effectively
7.3.1

**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.
[nucleus-info-20210402-123316.txt](https://github.com/NickImpact/GTS/files/6249510/nucleus-info-20210402-123316.txt)

**To Reproduce**
Step 1, have a full party
Step 2, buy a pokemon and it vanishes

Step1, buy a pokemon with a special texture
Step2, throw it out and it'll be removed

**Expected behavior**

**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!

**Comment by NickImpact** [comment]
Fixed
