### ISSUE TITLE
Add more time when someone bids on an auction, and there's very little time left

### ISSUE THREAD

**Issue by 02Miki** [NickImpact/GTS#127]
**What are you trying to do?**
Players really love to "snipe" auctions at the super last second, which just causes people to hunt each other down
**Describe the solution you'd like**
A setting that allows us to make it so time gets added when someone bids on an action, only when there's not much time left
**Describe alternatives you've considered**
~~Murdering them~~ Nothing, really
**Anything else that might help?**
Not really, no

**Comment by NickImpact** [comment]
Simple enough to do. Will implement a top squad of elite assassins to watch over auctions, and snipe the snipers...

Oh no murder? Fine..... timer increase instead

**Comment by ojcastillo29** [comment]
Murder is the better solution

**Comment by 02Miki** [comment]
https://github.com/NickImpact/GTS/commit/2574e7c5e1b54fa636b91be835c7597eedc51bc5
