### ISSUE TITLE
GTS Not Loading Correctly

### ISSUE THREAD

**Issue by Georggge** [NickImpact/GTS#13]
Im justmaking a server to mess around on and GTS just doesn't want to work for me
says command doesnt exist and also says this in console

19.01 00:31:37 [Server] Server thread/ERROR [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=gts, name=GTS, version=3.0.0-PR4b-S7.0, description=A Sponge Representation of the Global Trading Station, source=/mods/GTS-3.0.0-PR4b-1.12.2.jar}
19.01 00:31:37 [Server] INFO java.lang.NullPointerException: null
19.01 00:31:37 [Server] INFO at ninja.leaping.configurate.SimpleConfigurationNode.getList(SimpleConfigurationNode.java:118) ~[spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at com.nickimpact.gts.configuration.GTSConfigAdapter.getList(GTSConfigAdapter.java:110) ~[GTSConfigAdapter.class:?]
19.01 00:31:37 [Server] INFO at com.nickimpact.gts.api.configuration.keys.ListKey.get(ListKey.java:22) ~[ListKey.class:?]
19.01 00:31:37 [Server] INFO at com.nickimpact.gts.api.configuration.keys.ListKey.get(ListKey.java:15) ~[ListKey.class:?]
19.01 00:31:37 [Server] INFO at com.nickimpact.gts.configuration.AbstractConfig.load(AbstractConfig.java:75) ~[AbstractConfig.class:?]
19.01 00:31:37 [Server] INFO at com.nickimpact.gts.configuration.AbstractConfig.load(AbstractConfig.java:24) ~[AbstractConfig.class:?]
19.01 00:31:37 [Server] INFO at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:922) ~[spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:235) ~[spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688) ~[?:1.8.0_131]
19.01 00:31:37 [Server] INFO at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:231) ~[spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113) ~[spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67) ~[spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.nickimpact.gts.configuration.AbstractConfig.loadAll(AbstractConfig.java:58) ~[AbstractConfig.class:?]
19.01 00:31:37 [Server] INFO at com.nickimpact.gts.configuration.AbstractConfig.init(AbstractConfig.java:42) ~[AbstractConfig.class:?]
19.01 00:31:37 [Server] INFO at com.nickimpact.gts.GTS.onInit(GTS.java:165) ~[GTS.class:?]
19.01 00:31:37 [Server] INFO at org.spongepowered.common.event.listener.GameInitializationEventListener_GTS_onInit17.handle(Unknown Source) ~[?:?]
19.01 00:31:37 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:371) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:232) [SpongeMod.class:1.12.2-2555-7.1.0-BETA-2840]
19.01 00:31:37 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
19.01 00:31:37 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
19.01 00:31:37 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
19.01 00:31:37 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?]
19.01 00:31:37 [Server] INFO at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?]
19.01 00:31:37 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
19.01 00:31:37 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
19.01 00:31:37 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
19.01 00:31:37 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
19.01 00:31:37 [Server] INFO at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
19.01 00:31:37 [Server] INFO at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
19.01 00:31:37 [Server] INFO at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:719) [Loader.class:?]
19.01 00:31:37 [Server] INFO at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:?]
19.01 00:31:37 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336) [FMLCommonHandler.class:?]
19.01 00:31:37 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
19.01 00:31:37 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]

These are the plugins/mods that I am running
http://prntscr.com/i2fwx6
also running the latest version of forge

Any help would be highly appreciated

**Comment by NickImpact** [comment]
Update to GTS PR5

**Comment by Georggge** [comment]
havent built a project in a while, getting this error when trying to build the gradle
http://prntscr.com/i2g8dc

**Comment by NickImpact** [comment]
Why are you trying to build the project? The project itself is already built and released under PR 5

**Comment by Georggge** [comment]
oh my bad I cant seem to find the download for it so I was under the assumption I was going to have to build it myself

**Comment by NickImpact** [comment]
Are you in the server owner discord? If not, then it’s kinda closed off for now because my hard drive recently failed.

**Comment by NickImpact** [comment]
One more note: you’ll need to reset your config, or fill in values for the blacklist. The issue is routing from that

**Comment by Georggge** [comment]
yeah im not in the server owner Discord so does that mean I cant get the newest version?
