### ISSUE TITLE
Increased EV's and GMax Gone

### ISSUE THREAD

**Issue by Jaackla** [NickImpact/GTS#133]
Running the very latest version of gts and on generations

If you add  a gmax to the gts it will lose the gmax
Also if you add a pokemon it will get an EV increase and if you take it bac koff then re add it'll get even more evs

![image](https://user-images.githubusercontent.com/36846537/119258358-2c39cd80-bbc1-11eb-9eb5-6d570a631005.png)

**Comment by NickImpact** [comment]
Resolved
