### ISSUE TITLE
Pokemon stat changes

### ISSUE THREAD

**Issue by Jaackla** [NickImpact/GTS#134]
Running latest versions with generations

This goes alongside my other report where the evs changes and gmax got lost on a pokemon, i did another test with a non gmax pokemon and If i kept listing it then removing it it would fully change the stats, the ivs stayed the same and the evs stayed the same but the stats kept changing

![image](https://user-images.githubusercontent.com/36846537/119274419-a7be6d80-bc07-11eb-8ab3-9163c38d2573.png)

![image](https://user-images.githubusercontent.com/36846537/119274423-ab51f480-bc07-11eb-98be-5bff82b61af8.png)

![image](https://user-images.githubusercontent.com/36846537/119274425-ae4ce500-bc07-11eb-9abc-f7fb611f34e0.png)

**Comment by NickImpact** [comment]
Should be resolved
