### ISSUE TITLE
gts add command did not react after use

### ISSUE THREAD

**Issue by GranTesoro86** [NickImpact/GTS#16]
Sponge Forge : spongeforge-1.10.2-2281-5.2.0-BETA-2274
PixelmonGenerations-1.10.2-1.4.1-universal
GTS-1.10.2-2.4.2

The background did not react when I executed / gts add 1 2000 without tolerance and message  

Can you solve it for me? I really need this feature

**Comment by NickImpact** [comment]
GTS is not built for 1.10.2, only 1.12.2
