### ISSUE TITLE
Help pls ;-;

### ISSUE THREAD

**Issue by Glozzo** [NickImpact/GTS#17]
Hi. For some reason i can't seem to sell items on gts. i'm pretty sure i'm doing it right but it just won't work. do i have to enable something in order for it to work? 
![untitled](https://user-images.githubusercontent.com/37179290/37149102-cb0f7342-229a-11e8-9080-5c849ce91d7d.png)

**Comment by Glozzo** [comment]
That doesn't work you have to input a slot,amount,price.

**Comment by Zimon4eR** [comment]
Github stuff... there is /gts sell item amount price
https://i.imgur.com/6sEpX1J.png

**Comment by Glozzo** [comment]
So this is what i get when i try to do that. 
![dee032de7e1c9450d67caf6b9ad3f4fb 1](https://user-images.githubusercontent.com/37179290/37149571-881ef4de-229c-11e8-93ce-2660c35f104c.png)

In game this is what it tells me. 
![6fb1d30444d9e228597d2756ac5877ad](https://user-images.githubusercontent.com/37179290/37149598-9ed91c04-229c-11e8-81e8-c61ac05f0d7c.png)

**Comment by Zimon4eR** [comment]
What version of GTS are you using? 
![screen](https://i.imgur.com/KHw8PQr.png)

**Comment by Glozzo** [comment]
I Pm'd my manager. waiting for a response now, i appreciate the help :)

**Comment by Zimon4eR** [comment]
Anyway, latest one is GTS-3.6.0-S7.1, update and it will work

**Comment by Glozzo** [comment]
Ok Thank you.

**Comment by NickImpact** [comment]
Zimon is correct, just simply update to latest. The slot function was removed in favor for just simply selecting the item in your hand.
