### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by Pyya** [NickImpact/GTS#18]
When I download it, it downloads as a folder which I obviously can't put in a server's mod folder. Is there a .jar file I should be looking for within the download? Just please tell me how to upload it to my server.

**Comment by Pyya** [comment]
Hello??

**Comment by NickImpact** [comment]
Downloads for the plugin are available via the server pack for reforged, or you can find downloads in the server owner discord channel for reforged servers

**Comment by Pyya** [comment]
Yeah, I got help on Pixelmon Support discord. Thanks though!
