### ISSUE TITLE
Can you let it run on BungeeCord

### ISSUE THREAD

**Issue by 879492767** [NickImpact/GTS#19]

**Comment by NickImpact** [comment]
Technically already does, just needs further syncing work.

**Comment by 879492767** [comment]
I think it can add a memory function that players can send their pokemon to other servers.

**Comment by 879492767** [comment]
Deposit function. it means only the owner can take.

**Comment by NickImpact** [comment]
If it is to obey other servers, it would also need to obey the server it comes from. So, if it appears on one, it appears on all connected to the same MySQL database.

**Comment by 879492767** [comment]
My server is divided into survival servers and several servers to relieve pressure, but pixelmon cao not be synchronized. If this function is implemented, can make every server's pokemon able to circulate, I'm looking forward to such a function.

**Comment by 879492767** [comment]
If the Pokemon of each server is able to circulate, the enthusiasm of the player will be more.

**Comment by NickImpact** [comment]
As it is, using a MySQL database already allows for pokemon to circulate. The only thing you’ll notice is that the data is only read at start up, and isn’t refreshed as of yet. Further syncing work will allow the data to refresh, so servers are essentially communicating with each other, even if they aren’t connected to a bungee cord instance.

To further state, I don’t plan to add any form of system like PokeBank. GTS is not designed for such, and such a feature deserves to be placed in an entirely different plugin.

**Comment by 879492767** [comment]
Thank you, pixelmon has some problems with MySQL date storage. The data is only read at start up, and the server TPS will reduce when the data become more varied, so I gave up this way. I am in China,  I don't know the server abroad. Most of the servers can't store and synchronize with MySQL, so I want to have plugin like PokeBank.

**Comment by 879492767** [comment]
And how further syncing work could do...

**Comment by NickImpact** [comment]
Perhaps another member of the community will take it upon themselves to add a PokeBank plugin. As for GTS, It’s built only for the selling/trading of whatever it contains.

**Comment by 879492767** [comment]
I might ask someone else to do such a plugin. Can you tell me how to read Pokemon's NBT and how to take away from a player and send out Pokemon to a player?

**Comment by NickImpact** [comment]
For the code, just refer to the entries package, and check out both the PokemonEntry and Pokemon classes. Those two classes will show you how I process the pokemon data.
