### ISSUE TITLE
NPE on scheduler at com.pixelmonmod.pixelmon.storage.ComputerBox

### ISSUE THREAD

**Issue by Rasgnarok** [NickImpact/GTS#25]
https://gist.github.com/Rasgnarok/346f9bd9016103dd6d74489b09530539

**Comment by NickImpact** [comment]
This looks like a Pixelmon problem?

**Comment by Rasgnarok** [comment]
First time I see this sort of erroring with the computer manager and GTS, it kept spamming over and over and forced a restart. Perhaps you can ask Jay in what context this is made, for as far as I can tell, only GTS causes this on my end. 

Maybe having some sort of fallback or additional information would help narrow down how it is happening, or maybe prevent it from happening again - this isn't my area of expertise either way.
