### ISSUE TITLE
Showing items/Pixelmon not working & throwing error.

### ISSUE THREAD

**Issue by HackoHaxsLord** [NickImpact/GTS#27]
Versions:
- GTS-3.10.1-S7.1
- Nucleus-1.4.6-S7.0-MC1.12.2
- spongeforge-1.12.2-2705-7.1.0-BETA-3361

Reproducing:
- Run the '/gts' command.
- Click the 'Show only Pokemon?' or 'Show only Items?' buttons.

Logs:
- Error when 'Show only Pokemon?' or 'Show only Items?' is enabled: https://pastebin.com/raw/9cDu0sFH
- Latest logs: https://pastebin.com/raw/mLdGbnAh
- fml-server-latest logs: https://pastebin.com/raw/s5EpdGDD

**Comment by NickImpact** [comment]
That’d have to be an incompatible build of
Impactor at play

**Comment by HackoHaxsLord** [comment]
The version of Impactor being used is 'Impactor-S7.1.0-1.3.0'

**Comment by HackoHaxsLord** [comment]
I switched the version of Impactor for the version provided with in the GTS ZIP. I am no longer getting the error but the version is the same and confirmed this by '/sponge plugins impactor'.
