### ISSUE TITLE
download

### ISSUE THREAD

**Issue by xXjojojXx** [NickImpact/GTS#28]
Hey The Pixelmon Team gave me your Site and i wanted to ask you where to download your mod for 1.12.2? we want use your awesome mod for our server  i hope you can send us an link to download it.

**Comment by NickImpact** [comment]
Download links will be published sometime today, namely on Ore and this repo

**Comment by xXjojojXx** [comment]
Ore?
repo?

**Comment by MomokaChan** [comment]
Did you release it? If so I cannot find anything on it or previous versions

**Comment by xXjojojXx** [comment]
thx

**Comment by NickImpact** [comment]
https://ore.spongepowered.org/NickImpact/GTS
