### ISSUE TITLE
Permission Bug

### ISSUE THREAD

**Issue by xXjojojXx** [NickImpact/GTS#29]
[https://imgur.com/a/pvpUAOW](url)
https://imgur.com/a/pvpUAOW
hello, we installed the GTS Sidemod and did all permission, we can open the GTS but that's all we cannot sell Pokemon or add them we can not use any other command then it shown this (Picture Link) maybe you can help us what we need to do that all works fine ^^ if you need any iformation pls anwer what you need.

**Comment by NickImpact** [comment]
You are forgetting to specify the type of listing. For pokemon, it’s pokemon or poke. Item is just item. So /gts sell pokemon (args)

**Comment by NickImpact** [comment]
No, the literal word pokemon

**Comment by sapphirepixelmon** [comment]
Okay /gts sell item <amount> <price> does work. This is not clear in the documentation at all. Maybe show a message with the correct command format if a command is typed wrong.
