### ISSUE TITLE
Can't sell item

### ISSUE THREAD

**Issue by Flashback083** [NickImpact/GTS#3]
Hello ! 
Version of server : Minecraft SpongeForge 1.12.2
Version of sidemod : GTS-3.0.0-PR3b-1.12.2.jar
Description : 
/gts add item 1 1 1
or 
/gts sell item 1 1 1
don't work
Result error : 

"Unable to find an item in the specified inventory position..."

Screen : https://gyazo.com/c4dbf398bdf0cea60897373c5c27047b
Thanks !

**Comment by NickImpact** [comment]
Item's are currently broken for anyone not under the Sponge release builds. I decided to compile against the release with breaking changes for the experimental builds, so things have gone a little wacky. If you are on the release builds, let me know so I can get this properly tested and fixed.

**Comment by Flashback083** [comment]
Yep i'm on version : 
spongeforge-1.12.2-2555-7.1.0-BETA-2817.jar
(stable and i think release ?)

**Comment by PixelmonPRO** [comment]
Have this error too, `PR4b` `1.12.2-2555-7.1.0-BETA-2833`

**Comment by NickImpact** [comment]
This is now due to a Sponge API issue. Unfortunately, we have to wait on them for it to be fixed.
