### ISSUE TITLE
Opening the market just returns a server error.

### ISSUE THREAD

**Issue by Casey110405** [NickImpact/GTS#34]
I installed GTS and ran the sell command, but all it did was return this error in console: ivs.java.lang.NoSuchFieldError : ivs

**Comment by NickImpact** [comment]
Pixelmon Version and GTS version please

**Comment by Casey110405** [comment]
Pixelmon Generations v2.2.1 on GTS version 3.11-S7.1

**Comment by NickImpact** [comment]
Pixelmon Generations is currently unsupported due to their change in codebase from Reforged. I have no plans to add support for Generations.
