### ISSUE TITLE
GTS with mysql config don't work

### ISSUE THREAD

**Issue by Flashback083** [NickImpact/GTS#4]
Hello again ! 
Version of server : Minecraft SpongeForge 1.12.2
Version of sidemod : GTS-3.0.0-PR3b-1.12.2.jar
Description :
The GTS say an error when server startup

Result error :
**[15:51:19] [Server thread/INFO]: GTS » Now entering the init phase
[15:51:19] [Server thread/INFO]: GTS » Loading configuration...
[15:51:19] [Server thread/INFO]: GTS » Initializing commands...
[15:51:19] [Server thread/INFO]: GTS » Initializing listeners...
[15:51:19] [Server thread/INFO]: GTS » Loading storage provider... [MySQL]
[15:51:19] [Server thread/INFO]: GTS (Error) An error occurred whilst initializing the database...
[15:51:19] [Server thread/INFO]: GTS » Loading data into cache...
[15:51:19] [Server thread/INFO]: GTS » Initialization complete!**

gts.conf : 
# Which storage method the plugin should use.
#
# Currently supported: mysql, h2
#
# Fill out connection info below if you're using MySQL
storage-method="mysql"

data {
  # Uses standard DB engine port by default
  # MySQL: 3306
  # Specify as "host:port" if differs
  address="localhost"
  database="nameofdatabase*"
  username="myuser"
  password="MyPassword"

Screen : https://gyazo.com/48c9da1703914144e931600afe0f802d
Thanks !

**Comment by NickImpact** [comment]
Is the data information here filled in with what your MySQL settings are setup for? If not, then the error here is that it was unable to connect to the database.

**Comment by Flashback083** [comment]
I filled with my data information, and i got this error, but other sponge plugin work well, but i will make somes test to check if its my bad or not ^^

**Comment by NickImpact** [comment]
If you are able to, please check your fml-server-latest and fml-junk files. They should contain the stacktrace for the error.

**Comment by Flashback083** [comment]
https://pastebin.com/WgpD4rvt
Sql syntax ?

**Comment by NickImpact** [comment]
Was on my end with table creation, will be fixed in next PR
