### ISSUE TITLE
 Could not pass FMLInitializationEvent to Plugin

### ISSUE THREAD

**Issue by MstrTaffy** [NickImpact/GTS#41]
**What is the bug?**
Getting an error when server starts up

**What version of GTS are you running?**
3.11.3-S7.1
**What version of Sponge are you running?**
spongeforge-1.12.2-2768-7.1.4

**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.

**To Reproduce**
Start Server
Wait for Init
Error

**Expected behavior**
Clear Server logs

**Error logs**

Line 159 -201

[latest.log](https://github.com/NickImpact/GTS/files/2800016/latest.log)

**Comment by NickImpact** [comment]
Update to Impactor 1.4.1, and this issue should be resolved. It is available through my discord as of current, either in its release channel, or bundled in the new GTS update.

**Comment by MstrTaffy** [comment]
@NickImpact can I grab a discord link then please?
