### ISSUE TITLE
Update for Pixelmon Reforged 7.0.1

### ISSUE THREAD

**Issue by xion87** [NickImpact/GTS#45]
Hi, the latest GTS don't work anymore with Pixelmon Reforged 7.0.1, i would like to be updated for this pixelmon version

**Comment by NickImpact** [comment]
https://discord.gg/DSUDgwr
New builds have been available for 7.0.x for about 2 weeks now

**Comment by Feutor** [comment]
Can you redo that link ? I cannot join the discord

**Comment by 02Miki** [comment]
https://discord.gg/Bnp8aWw
