### ISSUE TITLE
Bug report command

### ISSUE THREAD

**Issue by Levy26** [NickImpact/GTS#49]
**What is the bug?**
It happens when I use the /Gts command

**What version of GTS are you running?**
GTS-S7.1-4.1.3

**What version of Sponge are you running?**
spongeforge-1.12.2-2768-7.1.6-RC3627

**Provide a link to the file generated by `/nucleus info`**
https://hastebin.com/helunibocu.sql

**To Reproduce**
Use command /Gts

**Expected behavior**
show miscellaneous gts commands

**Error logs**
https://hastebin.com/pasavelape.rb

**Comment by NickImpact** [comment]
Update impactor to 1.4.5

**Comment by Levy26** [comment]
Thank you very much.

One tip, it would be interesting to download the impactor next to the gts.
For example in a .zip file.

**Comment by NickImpact** [comment]
Did this before, and people still didn’t update despite this. So it honestly makes little to no difference.
