### ISSUE TITLE
Lore in GTS Gui don't appear

### ISSUE THREAD

**Issue by Flashback083** [NickImpact/GTS#5]
It's me again ! 
Version of server : Minecraft SpongeForge 1.12.2
Version of sidemod : GTS-3.0.0-PR3b-1.12.2.jar
Description :
/gts and when we hover the "Player info" or "sort" or "Your listings", the "lore" don't appear
Result error :

No message.

Screen :
https://gyazo.com/18fd4477e705934fc5d43ce59683160e
https://gyazo.com/b73dd93be2a61e0848fec04446782f78

Thanks a lots for your sidemod !

**Comment by NickImpact** [comment]
Something I forgot to add in, yet added to the message config. Shouldn't take long to add in!
