### ISSUE TITLE
Config option to disable item sales does not work

### ISSUE THREAD

**Issue by Sneebly** [NickImpact/GTS#50]
**What is the bug?**
The config option to disable item sales does not work

**What version of GTS are you running?**
GTS-Reforged-7.0.1-S7.1-1.1.2
GTS-S7.1-4.1.3
Impactor-S7.1.5-1.4.5

**What version of Sponge are you running?**
SpongeAPI: 7.1.0-6eb292fd
Sponge: 1.12.2-7.1.5-SNAPSHOT
SpongeForge: 1.12.2-2768-7.1.5-RC3512

**Provide a link to the file generated by `/nucleus info`**
https://pastebin.com/NGsXHurs

**Comment by NickImpact** [comment]
Fixed in 2e1b7999e43a207546fc24bb8f2ec155bec63938
