### ISSUE TITLE
Command Problem :l

### ISSUE THREAD

**Issue by SlendyOff** [NickImpact/GTS#51]
**What is the bug?**
When I run the command /gts nothing happens :l

**What version of GTS are you running?**
GTS-S7.1-4.1.3
GTS-Reforged-7.0.1-S7.1-1.1.2
Impactor-S7.1.5-1.4.5

**What version of Sponge are you running?**
Sponge 1.12.2-2768-7.1.4 Stable

**Provide a link to the file generated by `/nucleus info`**
https://pastebin.com/KLyndq8f

**To Reproduce**
1. Run the server
2. Run the command /gts
3. Nothings happen:l

**Comment by NickImpact** [comment]
GTS requires an Economy Service in order to function, otherwise, it'll disable itself to act as if it isn't even installed. The Pixelmon Economy Bridge alone is not enough, you will need a proper Sponge plugin which implements the EconomyService.

**Comment by SlendyOff** [comment]
ok sr (im new on sponge xD) :D!

**Comment by iMystxc** [comment]
yea should work with that

**Comment by NickImpact** [comment]
Closing as I assume this is now taken care of
