### ISSUE TITLE
No showing prices or anything.

### ISSUE THREAD

**Issue by BrandHyde** [NickImpact/GTS#53]
**What is the bug?**
Gts not showing price, seller or anything.

**What version of GTS are you running?**
1.1.2 (Latest)

**What version of Sponge are you running?**
RC3616

**Provide a link to the file generated by `/nucleus info`**
https://hastebin.com/aparaneven.sql

**To Reproduce**
1. Add something to GTS
2. Look in gts, the placeholders are just blank.

**Expected behavior**
It should show price, but it doesnt just empty spaces.

**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!

**Comment by iMystxc** [comment]
your versions are out of date. upgrade them to,
GTS 1-4.1.4
GTS-Refored 7-0.1-S7-1-1.1.3
Impactor S7.1.5-1.4.5

**Comment by NickImpact** [comment]
GTS is also currently incompatible with Nucleus 1.10 due to a change in its loading order. I’ll possibly make an update for that today, as the internal rewrite I’m working on is taking slightly longer than anticipated.

**Comment by Zancrow321** [comment]
> GTS is also currently incompatible with Nucleus 1.10 due to a change in its loading order. I’ll possibly make an update for that today, as the internal rewrite I’m working on is taking slightly longer than anticipated.

Was this published already? I still have the same issue.

**Comment by iMystxc** [comment]
yes, it's in his discord

**Comment by iMystxc** [comment]
https://discord.gg/Zbf9a5K
