### ISSUE TITLE
im change princing im reforged.conf but in server not change

### ISSUE THREAD

**Issue by xdreturns** [NickImpact/GTS#57]
**What is the bug?**

**What version of GTS are you running?**
GTS:vS7.1-4.1.5 Reforged: v1.1.2

**What version of Sponge are you running?**
spongeforge 1.12.2-2825-7.1.7

**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.

**To Reproduce**

**Expected behavior**
im change princing im reforged.conf but in server not change

**Error logs**
no error

**Comment by HackuJacku** [comment]
None of this makes sense. Full everything out as asked and not just certain parts of the format please.
