### ISSUE TITLE
Pixelmon Reforged gts doesn't work

### ISSUE THREAD

**Issue by Gelox1209** [NickImpact/GTS#58]
**What is the bug?**
When using gts and clicking the sell pokemon option on pixelmon reforged, the gui disappears and nothing comes up.

**What version of GTS are you running?**
GTS-S7.1-4.1.3.jar with GTS-Reforged-7.0.1-S7.1-1.1.2.jar

**What version of Sponge are you running?**
Sponge recommended: 1.12.2-2825-7.1.6

**Provide a link to the file generated by `/nucleus info`**
https://drive.google.com/file/d/1br-hS9X4AaoVF-tmK7NNHSa-bKbiYPQQ/view?usp=sharing

**To Reproduce**
1. /gts sell
2. Click on the sell pokemon option
3. Nothing pops up and error comes up.

**Expected behavior**
The gui to pop up and be able to choose what pokemon to sell.

**Error logs**
https://pastebin.com/FSJMmG8G

**Comment by NickImpact** [comment]
Update to 4.1.5

**Comment by R3bka** [comment]
Link to 4.1.5? i Cant find it

**Comment by NickImpact** [comment]
https://discord.gg/F93ZyuB

Check the releases channel in the GTS category

**Comment by erik131313** [comment]
I'm having the same problem on the 5.0.3 version. Items work but not pokemon.
