### ISSUE TITLE
GTS Breaks when a command is done

### ISSUE THREAD

**Issue by ThePurplecliffe** [NickImpact/GTS#59]
What is the bug?
we are trying to get the gts plugin up but its not working when we try to get Pokemon to sell it wont let us if we try to do /gts sell Pokemon (slot #) (price) it breaks the gts and doesn't allow anyone to use gts. This is the error we were getting after it broke com/pixelmonmod/pixelmon/util/helpers/SpriteHelper. also when we try to sell items it doesn't show who's selling it, doesn't show the price and it doesn't show the time

What version of GTS are you running?
4.1.3

Do you run any extensions? If so, list them here! (e.g. GTS-Reforged-*.jar)

What version of Sponge are you running?
Sponge 7.1.6

Provide a link to the file generated by /nucleus info
nucleus-info-20190712-172131.txt

To Reproduce
1. do /gts sell Pokemon (slot #) (price)
2. then when u try to do /gts it doesn't work and the error pops up
1. if u try to sell an item it doesn't show the price, seller, or time left

Expected behavior
we should be able to sell Pokemon and items

Error logs
com/pixelmonmod/pixelmon/util/helpers/SpriteHelper

**Comment by NickImpact** [comment]
Update to the 5.0 series, available in my discord
