### ISSUE TITLE
Config option to disable item sales does not work (again)

### ISSUE THREAD

**Issue by TalonPhoenix** [NickImpact/GTS#60]
**What is the bug?**
Disabling item sales in the config does not disable them from happening in-game.

**What version of GTS are you running?**
GTS-Sponge-1.12.2-5.0.1.jar
GTS-Sponge-Reforged-7.0.6-5.0.1.jar
Impactor-Sponge-7.1.5-2.0.0-DEV.jar

**What version of Sponge are you running?**
Spongeforge 1.12.2-2768-7.1.6-3616

**Provide a link to the file generated by `/nucleus info`**
https://pastebin.com/VdxsHUTA

**To Reproduce**
1. Under entries - items, set enabled=false
2. Try selling an item in GTS

**Expected behavior**
Item sales should be disabled in GTS, but players can still sell items.

**Error logs**
None

**Comment by NickImpact** [comment]
Fixed in 5.1.0
