### ISSUE TITLE
GTS with reforged bridge goes wrong

### ISSUE THREAD

**Issue by wujichen158** [NickImpact/GTS#61]
**What is the bug?**
When I add a pokemon like my Magikarp with /gts sell pokemon 1 10000, it goes well. But if I try to use /gts to see it then, it says “Error occurred while executing command: com/pixelmonmod/pixelmon/util/helpers/SpriteHelper”, and I cannot open the GUI of GTS.

I've noticed that someone has a similar problem, and you said that you put your latest version 4.1.5 on your discord. But I hope that if you could put it in github or sponge as well at your convenience. Thanks for providing me a good GTS :)

**What version of GTS are you running?**
GTS Reforged Bridge 1.1.2
GTS S7.1-4.1.3
Impactor  1.4.5

**What version of Sponge are you running?**
spongeforge 2768

**Provide a link to the file generated by `/nucleus info`**
https://pastebin.com/Vmw5fjXV

**To Reproduce**
1. use /gts sell pokemon <position in party> <price> to sell a pokemon.
2. The server tells me it goes well.
3. I run the command /gts

**Expected behavior**
I just hope that it can goes well

**Error logs**
In game:
Error occurred while executing command: com/pixelmonmod/pixelmon/util/helpers/SpriteHelper

**Comment by NickImpact** [comment]
Update to latest builds of GTS and Impactor
