### ISSUE TITLE
Duplicating Pixelmon GTS

### ISSUE THREAD

**Issue by Wolfhound645** [NickImpact/GTS#62]
What is the bug?
When a pokemon auction expires in GTS via running out of time, the pokemon will continually duplicate inside the players PC until the PC is full.

What version of GTS are you running?
5.0.3

What version of Sponge are you running?
Sponge 7.1.6

Provide a link to the file generated by /nucleus info
https://drive.google.com/file/d/13LsnRok-MvJzcekNnOsrcGNPs3cNRk2E/view

To Reproduce
/gts sell "slot number" ...This allows a pokemon listed on the GTS. Just wait until it expires naturally from time and it will duplicate into the PC, throwing the errors below.

Expected behavior
The pokemon returns to the party or PC. Once and only once.

Error Logs
![Error logs](https://user-images.githubusercontent.com/53977244/62824535-51cd2280-bb65-11e9-8259-39c5c23b376a.png)

**Comment by 02Miki** [comment]
Update impactor to latest
