### ISSUE TITLE
Generations cleared listings issue

### ISSUE THREAD

**Issue by Stampede2011** [NickImpact/GTS#64]
**What is the bug?**
Listings in the GTS get cleared on server restart for the Generations version. Previously reported this issue but I have not noticed any fix yet so I thought I should make an issue report.

**What version of GTS are you running?**
GTS-Sponge-1.12.2-5.0.3
GTS-Generations-2.6.2-7.1.5-5.0.3

**What version of Sponge are you running?**
1.12.2-2768-7.1.6-RC3616

**Provide a link to the file generated by `/nucleus info`**
https://gist.github.com/Stampede2011/2a704b2914fb12714369cf7d3a9e3a37

**To Reproduce**
1. Setup the GTS with a Generations server
2. Add items into the GTS
3. Restart the server
4. Check the GTS

**Expected behavior**
GTS listings are supposed to remain in the GTS after restart. 

**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!
https://gist.github.com/Stampede2011/7982c6550dc2b77ef6ffa85ad100df5b

https://i.gyazo.com/31a36a7168ba3215f6e518465db68c7f.png

**Comment by NickImpact** [comment]
Should be fixed in upcoming 5.1.0 build
