### ISSUE TITLE
[Suggestion] Make /gts sell simpler in none Pixelmon server.

### ISSUE THREAD

**Issue by Nekoyue** [NickImpact/GTS#65]
For none Pixelmon server, players can use this command to put items on the listing:
`/gts sell <total price> [<amount>]`
If the amount is not specified, it will be the number of items this player is holding.

**Comment by NickImpact** [comment]
So, the reason the classification option exists in that command is that, while a vanilla server might only have item support, the developer API permits that you can supply your own types of options to be input here. Regardless, I've added support for the upcoming version to default to the only registered option if any exist and only 1 exists. For most cases, this means it'll just default to the item menu.
