### ISSUE TITLE
/gts sell pokemon doesnt work.

### ISSUE THREAD

**Issue by SonkyTV** [NickImpact/GTS#69]
**/gts sell pokemon doesnt work.**

**What version of GTS are you running?**
GTS-Sponge-1.12.2-5.0.3.jar.

**What version of Sponge are you running?**
spongeforge-1.12.2-2838-7.1.7-RC3911.jar

**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.

**To Reproduce**
1. i type /gts sell pokemon 5000
2. than the normal gts window open
3. i dont can pick a pokemon
4. Nor Eror

**Expected behavior**

**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!

**Comment by NickImpact** [comment]
So you didn’t post the nucleus info report, which makes me believe your likely issue is that you didn’t install the proper pixelmon extension for GTS to work with pixelmon. Can only confirm that with that report or a picture of your plugins.
