### ISSUE TITLE
/GTS Sell Not working Properly

### ISSUE THREAD

**Issue by BarcodeGIT** [NickImpact/GTS#70]
**What is the bug?**
Use /GTS Sell, GUI Opens, CLick Sell item button, Window closes, Nothing happens

**What version of GTS are you running?**
You can simply mention the jar's name to ease this process.
GTS Sponge Reforged 7.07-5.0.3 & GTS-Sponge-1.12.2-5.0.3

**What version of Sponge are you running?**
Please tell us what version of Sponge you're on, so we can triage effectively
Spongeforge 1.12.2-2838-7.1.7-RC3880
**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.

**To Reproduce**
1. Type /GTS sell
2. Click on Sell Item
3. Window Closes
4. Nothing Happens

**Expected behavior**
Should be able to choose item to sell and at a price
**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!

**Comment by NickImpact** [comment]
Install an economy plugin

**Comment by BarcodeGIT** [comment]
yes sir o7, thank you sir o7
