### ISSUE TITLE
Project configuration problems

### ISSUE THREAD

**Issue by PixelPerfect** [NickImpact/GTS#72]
**What is the bug?**
Building from the current master produces errors when importing into an IDE (see the first error in errors section)

Removing blossom and manually setting version replacements to bypass this issue results in the second error in the errors section.

**What version of GTS are you running?**
Latest master.

**What version of Sponge are you running?**
n/a

**Provide a link to the file generated by `/nucleus info`**
n/a

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the project on a clean OS
2. Open the project in IntelliJ

**Expected behaviour**
Importing should complete allowing a local build to be performed.

**Error logs**
Error 1:
`Build file 'F:\***\***\***\GTS-master\build.gradle' line: 17
An exception occurred applying plugin request [id: 'ninja.miserable.blossom', version: '1.0.1']
> Failed to apply plugin [id 'ninja.miserable.blossom']
   > Could not create an instance of type ninja.miserable.blossom.BlossomExtension.
      > com.google.common.collect.HashMultimap.create()Lcom/google/common/collect/HashMultimap;`

Error 2:
`Build file 'F:\***\***\***\GTS-master\generations\build.gradle' line: 14
A problem occurred evaluating project ':generations'.
> Failed to apply plugin [id 'net.minecraftforge.gradle.forge']
   > Could not create plugin of type 'ForgePlugin'.
      > com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V`

**Comment by NickImpact** [comment]
Your using a different version of gradle. GTS uses 4.9

**Comment by PixelPerfect** [comment]
On further testing, this occurs when building using the GitLab-ci and a GitLab fork. I added the dependencies needed for blossom in this build and received the following build errors https://hastebin.com/hafizayusa.rb

**Comment by NickImpact** [comment]
You need impactor provided as a jar library. The maven repository it was hosted on has since died and I don’t currently have a server available for deploying it

**Comment by JordanWWood** [comment]
Why not just put impactor on one of the public maven repos, perhaps a bintray since its free for public repos?

**Comment by JordanWWood** [comment]
Could you compile a version and add it as a release?

**Comment by NickImpact** [comment]
I can consider those options, when I have time. For now, if you desire to compile GTS, you will need Impactor in your libs folder

**Comment by PixelPerfect** [comment]
After days of repeated attempts to build this, I've had to give up for time. I have this issue too but there are no binary versions that have been uploaded recently anywhere that I can see. Can you please direct me to where the newly updated binaries are uploaded or publish them on Ore or as a GitHub release?

**Comment by NickImpact** [comment]
All latest releases will always be posted in my discord
