### ISSUE TITLE
Error trying to sell Pixelmon (Sponge-Reforged)

### ISSUE THREAD

**Issue by HHServers** [NickImpact/GTS#73]
**What is the bug?**
Clicking the Pokeball icon in /gts sell gives this error in console, closes GUI
https://gist.github.com/HHServers/56b97432c811fbcebf49b208b0cffcfc
**What version of GTS are you running?**
You can simply mention the jar's name to ease this process.
GTS-Sponge-1.12.2-5.0.3.jar
GTS-Sponge-Reforged-7.0.7-5.0.3.jar
Impactor-Sponge-7.1.5-2.0.0-DEV.jar
**What version of Sponge are you running?**
Please tell us what version of Sponge you're on, so we can triage effectively
7.1.10 recommended
**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.
https://gist.github.com/HHServers/6528b96e5d4caff68a8cf3422c26700c
**To Reproduce**
1. Sponge 7.1.10, Pixelmon 7.2.2
2. GTS versions listed above
3. /gts sell

**Expected behavior**
Allow player to put their pixelmon for sale on GTS
**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!
https://gist.github.com/HHServers/56b97432c811fbcebf49b208b0cffcfc

**Comment by NickImpact** [comment]
Update to the latest reforged extension

**Comment by NyarukoDev** [comment]
After a days of repeated attempts to build this I've given up. I have this issue too but there are no binary versions that have been uploaded recently anywhere that I can see. Can you please direct me to where the newly updated binaries are uploaded or publish them on Ore or as a GitHub release?

**Comment by PixelPerfect** [comment]
After a days of repeated attempts to build this I've given up. I have this issue too but there are no binary versions that have been uploaded recently anywhere that I can see. Can you please direct me to where the newly updated binaries are uploaded or publish them on Ore or as a GitHub release?
