### ISSUE TITLE
pixelmon reforge can't buy pokemon

### ISSUE THREAD

**Issue by erposse90** [NickImpact/GTS#77]
version
GTS-S7.1-4.1.3
GTS-Reforged-7.0.1-S7.1-1.1.2
Impactor-S7.1.5-1.4.5
Nucleus-1.4.4-S7.0-MC1.12.2-plugin

with a more updated version of nucleus, the 1.14, gave the problem that did not show the name of the objects, the name of the sellers, the amount of money, etc.
now everything is functional except the fact that it does not buy pokemon!
you can put them up for sale and display them on the gui, but by clicking on it nothing happens :(
pls help me

**Comment by erposse90** [comment]
Sponge 7.1.0

**Comment by NickImpact** [comment]
Use the correct versions (5.2.3)

**Comment by erposse90** [comment]
Version of gts reforge or normal gts? 5.  2.3 I don't find it, only 5.0.3 of gts reforge but it is for sponge 7.2
