### ISSUE TITLE
No Pixelmon Info Showing

### ISSUE THREAD

**Issue by OzzyMar123** [NickImpact/GTS#81]
**What is the bug?**
I have installed everything yet info about hte pixelmon will not show up in the /gts menu
![image](https://user-images.githubusercontent.com/61271378/80861519-116b8280-8c67-11ea-90e6-99bbd669a288.png)

**What version of GTS are you running?**

GTS-S7.1-4.1.3.jar

**What version of Sponge are you running?**

spongeforge-1.12.2-2838-7.1.10.jar

**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.

[nucleus-info-20200502-112213.txt](https://github.com/NickImpact/GTS/files/4567484/nucleus-info-20200502-112213.txt)

**Expected behavior**
I expected it to show the info

**Comment by NickImpact** [comment]
You are about a year+ out of date. Update.
