### ISSUE TITLE
Gts crashes when selling Pokemon

### ISSUE THREAD

**Issue by rdy2rockjhr** [NickImpact/GTS#82]
**What is the bug?**
A clear and concise description of what the bug is. After selling a Pokemon, it returns the error,
"I'm sorry, but there was and error performing this command." After this any other GTS commands return the same error. I am giving permission to use command through Luckperms.

**What version of GTS are you running?**
GTS-Sponge-1.12.2-5.0.3

**Do you run any extensions? If so, list them here! (e.g. GTS-Reforged-*.jar)**
GTS-Sponge-Reforged-7.0.7-5.0.3

**What version of Sponge are you running?**
spongforge-1.12.2-2768-7.1.5
[latest.log](https://github.com/NickImpact/GTS/files/4629295/latest.log)

**Provide a link to the file generated by `/nucleus info`**
This tells us more info about your environment.

**To Reproduce**

**Expected behavior**

**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!

**Comment by NickImpact** [comment]
You need to use 5.2.3
