### ISSUE TITLE
GTS not working

### ISSUE THREAD

**Issue by TR80R** [NickImpact/GTS#86]
**What is the bug?**
/gts command doesn't work in the chat nor does the gts menu open.

**What version of GTS are you running?**
GTS-Sponge-1.12.2-5.2.3.jar

**What version of Sponge are you running?**
1.12.2-2838-7.3.0

**Provide a link to the file generated by `/nucleus info`**
[nucleus-info-20200909-230905.txt](https://github.com/NickImpact/GTS/files/5198983/nucleus-info-20200909-230905.txt)

**To Reproduce**

**Expected behavior**
i wanted the gts menu to open and work

**Error logs**
Please upload your logs to gist or another paste service. Avoid hastebin!

**Comment by ojcastillo29** [comment]
Downgrade your Nucleus version as GTS currently does not support anything 2.0 and above. 

Also please ensure you have the following: 
Gts Sponge-Reforged requirements for 8.0.2:
GTS-Sponge-Reforged-8.0.0-5.2.4.jar
GTS-Sponge-1.12.2-5.2.4.jar
Impactor-Sponge-7.1.5-2.2.0-SNAPSHOT.jar

all available in there respective channels in the bidoof development discord: https://discord.gg/Jx2cMp.
