### ISSUE TITLE
Just, Commands Unknown/Can't Use Commands.

### ISSUE THREAD

**Issue by WaifuNat** [NickImpact/GTS#88]
**Bug/Issue:**
Nothing loads, it says it loads in console and log but no commands work server says the commands are unknown.

**GTS Versions:**
GTS-Sponge-1.12.2-5.2.3.jar
and
GTS-Sponge-Reforged-8.0.0-5.2.3.jar

**Sponge Version:**
7.3.0 (After also trying with 7.2.0)

**Nucleus Info:**
https://pastebin.com/vJwxKtZu

**To Reproduce**
Well all i did was try to use GTS, and run server as normal.

**Expected behavior**
For me to be able to use GTS.

**Error logs**
Could not pass the event ChangeServiceProviderEvent$Impl to an Event Listener!
https://pastebin.com/q77336uK

^ about 1/5th the actual log, because in 2 seconds i had 5x that amount in the paste bin.

**Comment by NickImpact** [comment]
GTS is incompatible with Nucleus 2. GTS 6 will remedy this
