### ISSUE TITLE
GTS not working (Unknown command)

### ISSUE THREAD

**Issue by SnowyB1** [NickImpact/GTS#89]
**What is the bug?**
I have installed the latest version of the GTS plugin (5.2.3) along with the impactor and reforged bridge and Nucleus, but when i go into my server and use the command, server says that that it is an unknown command, almos like if the plugin was not installed.

**What version of GTS are you running?**
Lates 1.12.2-5.2.3

**What version of Sponge are you running?**
1.12.2-2838 7.3.0

**Error logs**
[latest.log](https://github.com/NickImpact/GTS/files/5476001/latest.log)

**Comment by 02Miki** [comment]
nucleus version?

**Comment by NickImpact** [comment]
2.2.3. Downgrade to 1.14.6 until GTS is updated to 6.0.

**Comment by SnowyB1** [comment]
2.2.3-MC1.12.2-SpongeAPI7.3

**Comment by 02Miki** [comment]
yes

**Comment by SnowyB1** [comment]
thank you ir worked perfectly
