### ISSUE TITLE
Mysql, again ! ^^

### ISSUE THREAD

**Issue by Flashback083** [NickImpact/GTS#9]
Maybe this time its my bad but i prefer ask to be sure ^^
Version of GTS  : GTS 3.0.0 Pre-Release 4b
When server load : 

https://pastebin.com/aJt6raj2

(The table is created)

And if i try to add pixelmon to GTS  : 
https://pastebin.com/eniQq055

**Comment by NickImpact** [comment]
Interesting, so the connection is never established. That's gonna be a fun fix.

**Comment by Flashback083** [comment]
I don't know if it can help you but i try to make a GTS version in my server (i give up since i see your sidemod work again) but its work (the sql work) in 1.10.2
Maybe you can use it ? Or maybe not xD
(Main) https://pastebin.com/eMzNkCNV
(SQL) https://pastebin.com/AW7HSbUg

Thanks for your works !

**Comment by NickImpact** [comment]
Any word on this one after GTS PR 5?

**Comment by Flashback083** [comment]
I will test it in 1-2 hours, sorry, I tell you when I know! Thanks

**Comment by Flashback083** [comment]
Its working well, thanks !
