### ISSUE TITLE
Pokemon sellin issues

### ISSUE THREAD

**Issue by Fxilo** [NickImpact/GTS#96]
ı use 6ç.0.7 version and when ı use gts comman and clicking on sell a good its show only selling items section not pokemons how can ı fix that

**Comment by ojcastillo29** [comment]
You dont have the pixelmon extension file in the respective folder than
Installation instructions: Run your server with GTS first, files can be found under #gts-releases  and #impactor-releases, and then stop your server. Then navigate to the config directory, and find the EXTENSIONS directory. Place the pixelmon extension jar there that can be found in #reforged. Then, you'll have pixelmon support for Reforged! In the future please do not create an issue ticket and additionally add the question on the discord, choose one or the other.

**Comment by NickImpact** [comment]
You also did not use the issues template. Therefore, I’m closing this ticket
