### ISSUE TITLE
GTS failed to enable

### ISSUE THREAD

**Issue by ShiratsuYudachi** [NickImpact/GTS#97]
**What is the bug?**
GTS failed to enable

**What version of GTS are you running?**
6.0.9

**What version of Sponge are you running?**
spongeforge-1.12.2-2838-7.3.0

**Provide a link to the file generated by `/nucleus info`**
[nucleus-info-20201224-235207.txt](https://github.com/NickImpact/GTS/files/5740090/nucleus-info-20201224-235207.txt)

**To Reproduce**
1. drop it to mods/
2. start server 
3. see error

**Expected behavior**
enabled normally

**Error logs**
[latest.log](https://github.com/NickImpact/GTS/files/5740098/latest.log)

**Comment by ojcastillo29** [comment]
Gts Sponge-Reforged requirements for 8.1.2:
GTS-Sponge-6.0.9.jar
Impactor-Sponge-7.1.5-3.0.0.jar
protocolcontrol-0.0.2.jar+

Pixelmon Extension:
GTS-Extension-Reforged-6.0.9.jar

Installation instructions: Run your server with GTS first, and then stop your server. Then navigate to the config directory, and find the EXTENSIONS directory. Place the pixelmon extension jar there. Then, you'll have pixelmon support for Reforged!

**Comment by ShiratsuYudachi** [comment]
> Gts Sponge-Reforged requirements for 8.1.2:
> GTS-Sponge-6.0.9.jar
> Impactor-Sponge-7.1.5-3.0.0.jar
> protocolcontrol-0.0.2.jar+
> 
> Pixelmon Extension:
> GTS-Extension-Reforged-6.0.9.jar
> 
> Installation instructions: Run your server with GTS first, and then stop your server. Then navigate to the config directory, and find the EXTENSIONS directory. Place the pixelmon extension jar there. Then, you'll have pixelmon support for Reforged!

I installed protocolcontrol and looks like it solved 'Could not pass  FMLInitializationEvent' of Impactor, but GTS still cannot be enabled
[latest.log](https://github.com/NickImpact/GTS/files/5740146/latest.log)

**Comment by 02Miki** [comment]
You need an economy plugin, as the error states:
net.impactdev.gts.api.exceptions.LackingServiceException: org.spongepowered.api.service.economy.EconomyService  
Also, it'd be better if you uploaded your logs to services like pastebin

**Comment by ShiratsuYudachi** [comment]
thanks for your help, it now works. really a good mod
