### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by ShiratsuYudachi** [NickImpact/GTS#98]
I made a Chinese language file

[zh_cn.conf.txt](https://github.com/NickImpact/GTS/files/5742068/zh_cn.conf.txt)

**Comment by NickImpact** [comment]
Awesome, will take a look and integrate into the base plugin if approved

**Comment by ShiratsuYudachi** [comment]
another question, can I post GTS on mcbbs(a Chinese Minecraft Forum)? I will put https://ore.spongepowered.org/NickImpact/GTS 
 as the download link.

**Comment by NickImpact** [comment]
It's looking good for the most part, just a few untranslated lines I see in there. Once you get those done, I'll integrate into the next release, which will likely be 6.1.0, following tonight's 6.0.10 patch.

As for posting on a forum, feel free, but do keep download links posted to their original point of origin where possible. Though you're allowed to redistribute the content, you definitely don't want to be the one responsible for the plugin I'm sure.

**Comment by ShiratsuYudachi** [comment]
[zh_cn.conf.txt](https://github.com/NickImpact/GTS/files/5744307/zh_cn.conf.txt)
I translated the part of discord and some missing lines, but still there are some button like the switch between Quick Perchase and Auctions in browser as well as the arrows named 'previous page' and 'next page' that I can't found them in the language file. Perhaps the lore and name of them have already set in the code?

**Comment by NickImpact** [comment]
Those are fine, I believe that's coming from Impactor so GTS doesn't have the ability to translate them at this present moment. Something I should change for future versions.

Will double check and integrate with 6.1.0 changes.

**Comment by NickImpact** [comment]
Will update this ticket with the file provided and any new lang keys that are added, given some will be added with 6.1's new admin features.

**Comment by NickImpact** [comment]
Added as current in https://github.com/NickImpact/GTS/commit/595ea7a69ccde0bd4abdba1b625fcd4997288b98.

Will close this ticket as future updates to the default language file should be handled via pull requests. Thanks your your translations.
