### ISSUE TITLE
GTS FAILED TO LOAD  

### ISSUE THREAD

**Issue by LeonusDH** [NickImpact/GTS#99]
https://pastebin.com/EKktBteg

**Comment by 02Miki** [comment]
net.impactdev.gts.api.exceptions.LackingServiceException: Protocol Control  

You have not followed the instructions. You need Protocol Control

**Comment by NickImpact** [comment]
And... Miki beat me to it

**Comment by LeonusDH** [comment]
https://ore.spongepowered.org/IchorPowered/Protocol-Control ?

**Comment by LeonusDH** [comment]
Thanks for the help.
